### ISSUE TITLE
Handle host keys correctly

### ISSUE THREAD

**Issue by tinnightcap** [nubisproject/nubis-base#713] opened 2017-10-05 14:58 UTC
We need to set up a method to have hosts automatically update their host keys and then have all hosts update their system wide known hosts file. This is to remove the ssh host key warning that is typically simply accepted without verification.

**Comment by gozer** [comment] 2017-10-12 13:13
Duplicate of nubisproject/nubis-jumphost#91 and/or nubisproject/nubis-jumphost#92

**Closed by gozer** 2017-10-12 13:13 UTC
